replicaCount: 2

image:
  repository: bloodorangeio/memelordz
  tag: master
  pullPolicy: Always

git:
  commit: "dev"
  branch: "dev"

ingress:
  host: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8080

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
